### ISSUE TITLE
managedsoftwareupdate --auto Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gonchik/munki#100]
```
What steps will reproduce the problem?
1. Run managedsoftware --auto via launchd or via command line
2.
3.

What is the expected output? 
Download and install software with the key unattended_install set to true

What do you see instead?
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 746, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 644, in main
    unused_force_action = updatecheck.checkForceInstallPackages()
  File "/usr/local/munki/munkilib/updatecheck.py", line 3054, in checkForceInstallPackages
    now = NSDate.date()
NameError: global name 'NSDate' is not defined

What version of the product are you using? On what operating system?
0.7.1 Build 1214
10.6.7

Please provide any additional information below.
The dmg gets downloaded but not installed.
managedsoftware --installonly works fine.
```

Original issue reported on code.google.com by `roland_z...@mac.com` on 17 Jun 2011 at 10:26

**Comment by GoogleCodeExporter** [comment]
```
Looks like a missing 

from Foundation import NSDate

but I'll let Mr. Randolph take first crack at fixing since it happens in the 
code he most recently added...
```

Original comment by `gregnea...@mac.com` on 17 Jun 2011 at 9:47

**Comment by GoogleCodeExporter** [comment]
```
r1218
```

Original comment by `jr...@google.com` on 20 Jun 2011 at 8:22

**Comment by GoogleCodeExporter** [comment]
```
Marking as Fixed since John added the missing import.
```

Original comment by `gregnea...@mac.com` on 19 Jul 2011 at 4:05
- Changed state: **Fixed**
