### ISSUE TITLE
KeyError: 'Version'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gonchik/munki#123]
```
What steps will reproduce the problem?
1. Attempting to import a package into Munki 
2.
3.

What is the expected output? What do you see instead?
I expect to be prompted with the typical information related to the package 
name, version, description, etc. Instead, the message below is the error 
result. I have made no modification to the file since downloading it. It is a 
printer driver for a Ricoh Aficio 300SR

What version of the product are you using? On what operating system?
I am running Mac OS X 10.6.7 

Please provide any additional information below.
AUX-9f808f:~ knigh2sm$ /usr/local/munki/munkiimport ~/Desktop/r46905L9.dmg 
Traceback (most recent call last):
  File "/usr/local/munki/makepkginfo", line 616, in <module>
    main()
  File "/usr/local/munki/makepkginfo", line 452, in main
    catinfo = getCatalogInfoFromDmg(item, options)
  File "/usr/local/munki/makepkginfo", line 103, in getCatalogInfoFromDmg
    cataloginfo = munkicommon.getPackageMetaData(itempath)
  File "/usr/local/munki/munkilib/munkicommon.py", line 1390, in getPackageMetaData
    if (MunkiLooseVersion(infoitem['version']) >
KeyError: 'version'
```

Original issue reported on code.google.com by `shawn...@gmail.com` on 17 Oct 2011 at 1:06

**Comment by GoogleCodeExporter** [comment]
```
Is this driver available from a public download? If so, can you provide a URL?  
This sounds like a bad package.
```

Original comment by `gregnea...@mac.com` on 1 Nov 2011 at 4:43
- Added labels: **Type-Other**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
http://support.ricoh.com/bb/html/dr_ut_e/re/model/mpc30/mpc30en.htm

I was downloading the version for OS X 10.6 It will install just fine if you 
run it after downloading, which leads me to believe the package is fine. 
However, when importing it, you get the error above...Thanks for looking into 
this. 
```

Original comment by `shawn...@gmail.com` on 1 Nov 2011 at 4:47

**Comment by GoogleCodeExporter** [comment]
```
This is a really old package format  -- maybe 10.2 style?  -- which is missing 
a lot of the metainfo that Munki needs.  Munki really wants the 10.4 and later 
package formats.

Still, munkiimport/makepkginfo should fail more gracefully here.
```

Original comment by `gregnea...@mac.com` on 1 Nov 2011 at 4:55
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Addressed in git push:
   e5af297..8bd3bd3  master -> master
```

Original comment by `gregnea...@mac.com` on 1 Nov 2011 at 5:17
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
What does this resolution mean? I'm not very familiar with this....
```

Original comment by `shawn...@gmail.com` on 1 Nov 2011 at 5:25

**Comment by GoogleCodeExporter** [comment]
```
You'll need to either check out and test the latest code from the git 
repository, or wait for a packaged download to be created.

See http://code.google.com/p/munki/wiki/BuildingMunki for how to build from 
source.

-Greg
```

Original comment by `gregnea...@mac.com` on 1 Nov 2011 at 5:31
