### ISSUE TITLE
managedsoftwareupdate: "UnboundLocalError: local variable 'manifest' referenced before assignment"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gonchik/munki#2]
```
What steps will reproduce the problem?
1. setup Munki serveras per inc'l README
2. download and install munkitools-0.3.2.pkg.zip
3. install and edit /Library/Preferences/ManagedInstalls.plist
4. exec managedsoftwareupdate 


What is the expected output? What do you see instead?
- expected: managedsoftwareupdate should fetch the client manifest
- actual: Python error,
"Traceback (most recent call last):
  File "./managedsoftwareupdate", line 249, in <module>
    main()
  File "./managedsoftwareupdate", line 168, in main
    result = updatecheck.check(id=options.id)
  File "/usr/local/munki/munkilib/updatecheck.py", line 1429, in check
    mainmanifestpath = getPrimaryManifest(id)
  File "/usr/local/munki/munkilib/updatecheck.py", line 1208, in getPrimaryManifest
    if not manifest:
UnboundLocalError: local variable 'manifest' referenced before assignment"

What version of the product are you using? On what operating system?
0.3.2, Mac OS X Leopard 10.5.7

Please provide any additional information below.
- updatecheck.py: Python doesn't seem to like the 'if not manifest:' 
conditional statement on line 
1208
- Declaring manifest prior to the testing is a a fix but better maybe to use 
try/except blocks?


```

Original issue reported on code.google.com by `daygloje...@gmail.com` on 29 Jul 2009 at 4:58

**Comment by GoogleCodeExporter** [comment]
```
Committed revision 145 as a fix.
```

Original comment by `gregnea...@mac.com` on 31 Jul 2009 at 2:26
- Changed state: **Fixed**
