### ISSUE TITLE
NSInvalidArgumentException - Class OC_PythonObject: no such selector: _cfTypeID

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gonchik/munki#44]
```
What steps will reproduce the problem?
1. Upgrade to 0.7.0.887
2. /usr/local/munki/managedsoftwareupdate --checkonly

What is the expected output? What do you see instead?

bash-3.2# /usr/local/munki/managedsoftwareupdate --checkonly
preflight logged for GotvidMacPro

Managed Software Update Tool
Copyright 2010 The Munki Project
http://code.google.com/p/munki

ERROR: Could not retrieve catalog testing from server.   (that's fine, no 
packages in testing right now).
ERROR: Error 22: The requested URL returned error: 404
ERROR: Could not retrieve catalog testing from server.
ERROR: Error 22: The requested URL returned error: 404
ERROR: Could not retrieve catalog testing from server.
ERROR: Error 22: The requested URL returned error: 404
ERROR: Could not retrieve catalog testing from server.
ERROR: Error 22: The requested URL returned error: 404
The following items will be installed or upgraded:
    + AdobeFlashPlayer-10.1.102.64.0
        Adobe® Flash® Player is a cross-platform browser-based application runtime that delivers uncompromised viewing of expressive applications, content, and videos across screens and browsers.
ERROR: Unexpected error in updatecheck:
ERROR: Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 555, in main
    updatecheckresult = updatecheck.check(client_id=options.id)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2623, in check
    munkicommon.savereport()
  File "/usr/local/munki/munkilib/munkicommon.py", line 339, in savereport
    os.path.join(pref('ManagedInstallDir'), 'ManagedInstallReport.plist'))
  File "/usr/local/munki/munkilib/FoundationPlist.py", line 92, in writePlist
    dataObject, NSPropertyListXMLFormat_v1_0, None)
ValueError: NSInvalidArgumentException - Class OC_PythonObject: no such 
selector: _cfTypeID

Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 703, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 559, in main
    munkicommon.savereport()
  File "/usr/local/munki/munkilib/munkicommon.py", line 339, in savereport
    os.path.join(pref('ManagedInstallDir'), 'ManagedInstallReport.plist'))
  File "/usr/local/munki/munkilib/FoundationPlist.py", line 92, in writePlist
    dataObject, NSPropertyListXMLFormat_v1_0, None)
ValueError: NSInvalidArgumentException - Class OC_PythonObject: no such 
selector: _cfTypeID

Please use labels and text to provide additional information.

bash-3.2# defaults read /Library/Preferences/ManagedInstalls       
{
    AdditionalHttpHeaders =     (
        "Authorization: Basic XXXXXXXXXXXXXXXXXXX=="
    );
    ClientIdentifier = "litshum_sv_testing.plist";
    InstallAppleSoftwareUpdates = 1;
    LastCheckDate = "2010-11-15 12:20:00 +0100";
    LastCheckResult = 1;
    LastNotifiedDate = "2010-11-15 08:53:57 +0100";
    SoftwareRepoURL = "https://munki.xxx.gu.se:xxxx/";
}

```

Original issue reported on code.google.com by `MagerV...@gmail.com` on 15 Nov 2010 at 12:23

**Comment by GoogleCodeExporter** [comment]
```
I can't reproduce this, either by running managedsoftwareupdate --checkonly, or 
by calling FoundationPlist.writePlist() with various strange stuff...

I have to suspect there's something in munkicommon.report that 
FoundationPlist.writePlist() is choking on, but it's hard to guess what that 
might be.

If you can reliably reproduce it, try inserting a call to printreport into the 
savereport function, like so:

def savereport():
    """Save our report"""
    printreport(report)
    FoundationPlist.writePlist(report,
        os.path.join(pref('ManagedInstallDir'), 'ManagedInstallReport.plist'))

and see if we can discover any clues in the report output...

I'm using a newer build, but there have been no significant changes in the code 
around writing the reports to disk in a long time. 
```

Original comment by `gregnea...@mac.com` on 15 Nov 2010 at 6:00

**Comment by GoogleCodeExporter** [comment]
```
ERROR: Unexpected error in updatecheck:
ERROR: Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 555, in main
    updatecheckresult = updatecheck.check(client_id=options.id)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2623, in check
    munkicommon.savereport()
  File "/usr/local/munki/munkilib/munkicommon.py", line 338, in savereport
    printreport(report)
  File "/usr/local/munki/munkilib/munkicommon.py", line 333, in printreport
    printreportitem(key, reportdict[key])
  File "/usr/local/munki/munkilib/munkicommon.py", line 320, in printreportitem
    printreportitem(index, item, indent+1)
  File "/usr/local/munki/munkilib/munkicommon.py", line 325, in printreportitem
    printreportitem(subkey, value[subkey], indent+1)
  File "/usr/local/munki/munkilib/munkicommon.py", line 327, in printreportitem
    print indentspace*indent, '%s: %s' % (label, value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xae' in position 
18: ordinal not in range(128)

Lemme see if I can figure out what needs to be decoded...

```

Original comment by `MagerV...@gmail.com` on 16 Nov 2010 at 11:40

**Comment by GoogleCodeExporter** [comment]
```
With a repr(value) on line 327 we get:

 Errors:
     1: u'Could not retrieve catalog testing from server.'
     2: CurlDownloadError('Error 22: The requested URL returned error: 404',)
     3: u'Could not retrieve catalog testing from server.'
     4: CurlDownloadError('Error 22: The requested URL returned error: 404',)
     5: u'Could not retrieve catalog testing from server.'
     6: CurlDownloadError('Error 22: The requested URL returned error: 404',)
     7: u'Could not retrieve catalog testing from server.'
     8: CurlDownloadError('Error 22: The requested URL returned error: 404',)
     9: 'Unexpected error in updatecheck:'
     10: 'Traceback (most recent call last):\n  File "/usr/local/munki/managedsoftwareupdate", line 555, in main\n    updatecheckresult = updatecheck.check(client_id=options.id)\n  File "/usr/local/munki/munkilib/updatecheck.py", line 2623, in check\n    munkicommon.savereport()\n  File "/usr/local/munki/munkilib/munkicommon.py", line 340, in savereport\n    os.path.join(pref(\'ManagedInstallDir\'), \'ManagedInstallReport.plist\'))\n  File "/usr/local/munki/munkilib/FoundationPlist.py", line 92, in writePlist\n    dataObject, NSPropertyListXMLFormat_v1_0, None)\nValueError: NSInvalidArgumentException - Class OC_PythonObject: no such selector: _cfTypeID\n'
 RemovedItems:
 ItemsToInstall:
     1:
         installed_size: 12552L
         installer_item_size: 12552L
         display_name: u'Adobe Flash Player'
         forced_install: False
         description: u'Adobe\xae Flash\xae Player is a cross-platform browser-based application runtime that delivers uncompromised viewing of expressive applications, content, and videos across screens and browsers.'
         manifestitem: u'AdobeFlashPlayer'
         installed: False
         version_to_install: u'10.1.102.64.0'
         forced_uninstall: False
         installer_item: u'AdobeFlashPlayer-10.1.102.64.pkg'
         name: u'AdobeFlashPlayer'
 InstallResults:
 Warnings:
 MachineInfo:
     os_vers: '10.6.4'
     hostname: 'dhcp-xxxxxxx.xx.gu.se'
     arch: 'i386'
 ManagedInstalls:
     1:
         installed_size: 25517L
         installer_item_size: 25517L
         forced_install: False
         description: u'Adium is a free instant messaging application for Mac OS X that can connect to AIM, MSN, Jabber, Yahoo, and more.'
         manifestitem: u'Adium'
         installed: True
         forced_uninstall: False
         name: u'Adium'
     2:
         installed_size: 1089L
         installer_item_size: 1089L
         forced_install: False
         description: ''
         manifestitem: u'MunkiPreflightPostflight'
         installed: True
         forced_uninstall: False
         name: u'MunkiPreflightPostflight'
     3:
         installed_size: 13723L
         installer_item_size: 13723L
         forced_install: False
         description: ''
         manifestitem: u'Spotify'
         installed: True
         forced_uninstall: False
         name: u'Spotify'
     4:
         installed_size: 41533L
         installer_item_size: 41533L
         forced_install: False
         description: u'VLC is a powerful media player, playing most of the media codecs and video formats out there.'
         manifestitem: u'VLC'
         installed: True
         forced_uninstall: False
         name: u'VLC'
     5:
         installed_size: 19137L
         installer_item_size: 19137L
         forced_install: False
         description: u'Mozilla Firefox is a free and open source web browser.'
         manifestitem: u'Firefox'
         installed: True
         forced_uninstall: False
         name: u'Firefox'
     6:
         installed_size: 11977L
         installer_item_size: 11977L
         forced_install: False
         description: u"TextMate brings Apple's approach to operating systems into the world of text editors. By bridging UNIX underpinnings and GUI, TextMate cherry-picks the best of both worlds to the benefit of expert scripters and novice users alike."
         manifestitem: u'TextMate'
         installed: True
         forced_uninstall: False
         name: u'TextMate'
 ProblemInstalls:
 StartTime: '2010-11-16 12:42:10 +0100'
 RunType: 'custom'
 ItemsToRemove:
 RemovalResults:
 ManifestName: u'litshum_sv_testing.plist'
Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 703, in <module>
    main()
  File "/usr/local/munki/managedsoftwareupdate", line 559, in main
    munkicommon.savereport()
  File "/usr/local/munki/munkilib/munkicommon.py", line 340, in savereport
    os.path.join(pref('ManagedInstallDir'), 'ManagedInstallReport.plist'))
  File "/usr/local/munki/munkilib/FoundationPlist.py", line 92, in writePlist
    dataObject, NSPropertyListXMLFormat_v1_0, None)
ValueError: NSInvalidArgumentException - Class OC_PythonObject: no such 
selector: _cfTypeID
bash-3.2# 

```

Original comment by `MagerV...@gmail.com` on 16 Nov 2010 at 11:52

**Comment by GoogleCodeExporter** [comment]
```
Added a pickled report.
```

Original comment by `MagerV...@gmail.com` on 16 Nov 2010 at 11:53

Attachments:
- [munkireport.pickle](https://storage.googleapis.com/google-code-attachments/munki/issue-44/comment-4/munkireport.pickle)

**Comment by GoogleCodeExporter** [comment]
```
Does the error go away if Adobe Flash is not in the list of items to install?
```

Original comment by `gregnea...@mac.com` on 16 Nov 2010 at 4:31

**Comment by GoogleCodeExporter** [comment]
```
No, it appears to be triggered by the testing catalog not being found. If I 
place a testing catalog in the repository it runs fine.

(I'm only visiting this machine 3 times a week if you're wondering why the 
updates are so sporadic...)
```

Original comment by `MagerV...@gmail.com` on 18 Nov 2010 at 8:31

**Comment by GoogleCodeExporter** [comment]
```
Fixed in r919.

munkicommon.display_error() was appending the CurlDownloadError object to 
report['Errors'] instead of the error message as a string. When savereport() 
was called, FoundationPlist.writePlist() threw an exception when trying to 
write the unsupported object to the plist.

Fix is to coerce the error to a string before appending it to the 
report['Errors'] list. Made a similar fix to munkicommon.display_warning().

```

Original comment by `gregnea...@mac.com` on 18 Nov 2010 at 4:42
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Confirmed.
```

Original comment by `MagerV...@gmail.com` on 22 Nov 2010 at 8:09
- Changed state: **Verified**
