### ISSUE TITLE
Need som help with  CA config on Munki

### ISSUE THREAD

**Issue by GoogleCodeExporter** [gonchik/munki#68]
```
What steps will reproduce the problem?
1.
sudo /usr/local/munki/managedsoftwareupdate -vvv --checkonly

Managed Software Update Tool
Copyright 2010 The Munki Project
http://code.google.com/p/munki

Manifest base URL is: https://munki/repo/manifests/
ERROR: Unexpected error in updatecheck:
ERROR: Traceback (most recent call last):
  File "/usr/local/munki/managedsoftwareupdate", line 553, in main
    updatecheckresult = updatecheck.check(client_id=options.id)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2521, in check
    mainmanifestpath = getPrimaryManifest(client_id)
  File "/usr/local/munki/munkilib/updatecheck.py", line 2079, in getPrimaryManifest
    x509 = load_certificate(FILETYPE_PEM, data)
Error: [('PEM routines', 'PEM_read_bio', 'no start line')]


What is the expected output? What do you see instead?
Connection with munki server

What version of the product are you using? On what operating system?
munki =munkitools-0.7.0.1047.0, OS = Mac os x 10.6.7

Please provide any additional information below.

```

Original issue reported on code.google.com by `espen.th...@gmail.com` on 22 Mar 2011 at 8:38

**Comment by GoogleCodeExporter** [comment]
```
my ManagedInstalls.plist
```

Original comment by `espen.th...@gmail.com` on 22 Mar 2011 at 8:42

Attachments:
- [ManagedInstalls copy.plist](https://storage.googleapis.com/google-code-attachments/munki/issue-68/comment-1/ManagedInstalls copy.plist)

**Comment by GoogleCodeExporter** [comment]
```
Espen -- I think you'll get better responses if you post to the munki-dev group:

http://groups.google.com/group/munki-dev

-Greg
```

Original comment by `gregnea...@mac.com` on 22 Mar 2011 at 3:35
- Added labels: **Type-Other**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Based on the filename: '/Library/Managed 
Installs/certs/UTNAddTrustServer_CA.pem' I'm guessing this is cert for the 
Certificate Authority and not a cert for the client.

Have you worked through this document?
http://code.google.com/p/munki/wiki/UsingMunkiWithSSLClientCertificates

-Greg
```

Original comment by `gregnea...@mac.com` on 22 Mar 2011 at 5:40

**Comment by GoogleCodeExporter** [comment]
```
Addressed as support via munki-dev
```

Original comment by `gregnea...@mac.com` on 12 May 2011 at 5:14
- Changed state: **WontFix**
